language: php

php:
    - 7.0
    - 7.1

before_script:
    - composer install

script:
    - vendor/bin/phpunit --coverage-clover coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

branches:
    only:
        - master
